import React from 'react';
import "./Home.scss";

const Home = () => {
  return (
    <div>Home Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi nemo perspiciatis nulla enim id non quam officiis, quo molestiae dignissimos perferendis numquam voluptatibus voluptatum ipsum qui! Velit dolor voluptatibus voluptatum suscipit labore. Dolorem necessitatibus adipisci perferendis rerum praesentium modi cupiditate unde. Cumque minima aspernatur eveniet, ullam, velit qui molestiae cum adipisci, culpa quod iusto facilis explicabo recusandae ex eius sunt eum doloribus temporibus sed aliquid illo alias. Excepturi, velit vitae iusto perferendis minima, doloribus consequuntur recusandae, tempore sed molestias nulla! Voluptatibus aut voluptate, hic repellat repudiandae molestias ad dignissimos expedita facilis ut saepe voluptas quam velit aliquid perferendis at non provident eum! Quas eius ad earum dignissimos fuga et explicabo labore aliquam quo, voluptas vitae accusantium voluptate voluptates a illum facere temporibus illo iste commodi adipisci molestiae. Dolorum, at explicabo. Sunt, totam! Dolorum, est? Quia rerum officia non ipsum explicabo praesentium ex quasi eius quaerat repellendus voluptas, consectetur amet et, facilis quam sunt id quae sit ipsam numquam corrupti incidunt corporis doloremque cupiditate! Modi tenetur porro vitae vel, iste, perferendis animi deleniti aut ipsam sit quo. Praesentium voluptas temporibus molestiae cum distinctio natus illo rerum quisquam harum dolor, tenetur quam? Velit, praesentium mollitia! Commodi saepe dicta blanditiis placeat quibusdam modi porro inventore ipsam expedita! Magnam, mollitia. Deleniti repellendus earum ipsa sed eligendi laboriosam natus tempora! Consectetur sunt ad nostrum nihil, iusto placeat eligendi beatae neque soluta quaerat possimus id sit. Ex suscipit minus pariatur omnis cumque, ad eum veniam totam iure corporis dolorum molestias? Nisi quam quis voluptatibus eum rerum quibusdam fugit quae quod eligendi laudantium mollitia quia, modi explicabo optio repudiandae incidunt? Quo, aliquam sed! Dignissimos libero dolorem saepe recusandae ex autem, expedita tempora non in enim quasi minus quo nam id officiis. Facilis provident ab harum doloremque voluptate natus autem veritatis necessitatibus soluta pariatur, omnis doloribus in voluptatibus, id eveniet totam? Deserunt nesciunt quam molestias magni, fugiat excepturi dicta neque iusto voluptas sed non rem qui provident laborum ex eaque veritatis quae. Quod suscipit doloribus excepturi hic pariatur placeat, earum at architecto molestiae delectus, illum optio ratione porro eos maxime molestias ut eveniet consectetur repudiandae impedit? Autem ipsa quo iusto officia sit ex nesciunt consectetur incidunt quam iste facere, veniam beatae voluptatibus consequuntur eos eius labore nemo praesentium harum. Ex, atque assumenda in fugit possimus veritatis pariatur commodi nisi ipsum, doloremque ipsam mollitia est repudiandae deleniti! Doloremque vero deserunt voluptates, odio dolor error nisi veniam architecto vel magni!
    </div>
  )
}

export default Home